---
title: "Untitled"
author: "Lydia Warden"
date: "03/08/2021"
output: html_document
---
Masbrough: background information
-	Approx. 5% of the population in the Rotherham West ward (largely co-extensive with Masbrough) were born in non-UK EU countries (572). 591 residents were born in South Asia, 77 in the Middle East, 69 in Zimbabwe and 60 in Central and West Africa. Most respondents in the 2011 Census identified as ethnically White British, White European or British Pakistani. ‘The dense minorities communities in the ward are due to the affordability of local housing.’ (https://en.wikipedia.org/wiki/Masbrough).
o	Total population: 13262 (2011 Census in https://en.wikipedia.org/wiki/Masbrough)
-	Former industrial area, which produced lots of iron and brass amongst other products such as jars. (https://industrial-archaeology.org/wp-content/uploads/2017/05/1995-Industrial-History-of-South-Yorkshire.pdf).
-	Industrial structure: History of mining and manufacturing as major industries. (https://www.visionofbritain.org.uk/unit/10084763/cube/IND_SECTOR_GEN)
-	Significant fluctuations in unemployment rates since 1930: Large increase from 1970s to 1990s, significant drop between 1990 and 2000 but steadily increasing once again, c.8% in 2010. Higher than Great British average since 1970, approximately 1% higher in 2010 (https://www.visionofbritain.org.uk/unit/10084763/rate/CENSUS_MALE_UNEM).
-	The monks at Kirkstead Abbey near Kimberworth began smelting iron around 1160, and ‘the history of the area is heavily influence by industrial developments, especially in iron, steel and coal.’


Rotherham: background information
-	2011 demographic information (https://en.wikipedia.org/wiki/Rotherham):
o	Rotherham USD (urban subdivision): 85.6% White British, 8.3% Asian, 1.3% Black.
o	Rotherham (Borough): 91.9% White British, 4.1% Asian, 0.8% Black.
