---
title: "LSOA Boundaries - Development and Validation"
author: "Lydia Warden"
date: "27/07/2021"
output: html_document
---
LSOA Boundaries: Development and Validation
-	LSOAs were constructed from OAs and designed to contain between 1000 and 3000 residents and 400 to 1200 households. (Tower Hamlets, 2013, p4).
-	Changes were implemented between 2001 and 2011 to reflect population growth, in most cases leading to an increase in the number of LSOAs (Tower Hamlets, 2013, p7).
-	The ONS conducted consultations to gain feedback on proposed changes to output area boundaries ahead of the 2011 and 2021 censuses. Responses were given in the form of written feedback. A large proportion of respondents were representatives from councils and related organisations (ONS, 2021). The consultations requested feedback on proposed strategies for making changes to boundaries, rather than validation of the new boundaries (ONS, 2021).

Vickers, D. and Rees, P., (2007). Creating the UK National Statistics 2001 output area classification. Journal of the Royal Statistical Society: Series A, Statistics in Society. 170(2), pp.379-403.

-	P380 Area classification refers to the classification of areas into groups in the basis of the similarity of characteristics within them. One of the most commonly used area classifications is geodemographic classifications, which ‘works on the principle that the place and the population are inextricably linked.’ Information including age, ethnicity, education, employment and type of housing is used to find out about the people who live in an area, as if similar people live in similar places we can infer knowledge about others from knowledge about one.
-	P381 Classifications are created using cluster analysis.
-	P390-1 41 variables were selected for input to the classification
o	Demographic variables including age, ethnicity, proportion of the population that were foreign-born and population density.
o	Household composition: separated/divorced, single person households, single pensioner households, lone parent households, childless couples and households with non-dependent children.
o	Housing: renting, terraced, detached, flats, no central heating, average house size (no of rooms), people per room.
o	Socioeconomic: HE qualification, employment, 2+ cars, public transport to work, WFH, long-term limiting illness, providing unpaid care.
o	Employment: students, unemployed, part-time, proportions working in different industries.
-	P395 Selection of the number of clusters involved consultation with potential users and members of the ONS area classification advisory board.
-	P398 Each cluster was named based on the profile features that distinguish it from other clusters.
-	P399 Comments and suggestions on names were received from people who took part in a consultation exercise about the classification.

Martin, D., (2002). Geography for the 2001 Census in England and Wales. Population Trends. 108, pp.7-15.
-	P7 An important function of a census geography system is to provide a framework for the publication of small area census statistics.

-	P8 1991 and previous: Enumeration Districts (EDs) are used to ‘facilitate efficient and accurate distribution and collection of census forms by enumerators, while attempting to equalize enumerator workload.’ Aimed for ED boundaries not to straddle major roads, rivers, railway lines or extensive areas of open space. EDs also had to nest within wards and parishes/communities – which was particularly important in previous censuses when the EDs themselves were used as output areas.
-	P9 ED Design for 2001: Completed ED design using GIS, then re-planned certain areas using the latest available address-point data, which was supplemented by the findings from enumeration and processing (to ensure that the ED geography reflected the residential structure on census day as closely as possible).
-	P10 Output area design: attempted to construct OAs that, where possible, are assembled from whole unit postcodes to facilitate better integration between census and postcode geographies (previously a major challenge with 1991 EDs). Other important considerations included the standardisation of OA population sizes, maximisation of internal social homogeneity and less irregular geographical shaped areas.
-	P12 Measuring homogeneity: ‘An area which has provoked considerably interest in consultation with census users…’.
o	‘A particular concern of many users has been that EDs from previous censuses have often obscured social divisions, which would be of importance in the context of local service planning and resource allocation.’
o	Initial experiments with automated zone design used a simple homogeneity measure to maximise the uniformity of households falling within different categories (used tenure categories – owner occupied, privately rented, rented from LA or housing association). The dominant category may, however, account for less than half of households in areas with a good spread of tenure categories. Therefore, required a more sophisticated measure.
o	Tranmer and Steel discussed using intra-area correlation (IAC). P13 ‘Maximising IAC may be thought of as configuring OAs in such a way that the largest proportion of the variation in the relevant variable(s) between different postcode building blocks occurs across OA boundaries, while the smallest proportion occurs between postcodes inside the same OA.’
o	P13 Current proposal is to use 4 tenure categories and 7 dwelling type categories, combined with equal weighting to produce an overall homogeneity measure.
o	Shape: consultations found that census users would prefer OAs follow discrete settlements rather than possess compact shapes.

Qamer, F.M., Shehzad, K., Abbas, S., Murthy, MSR., Xi, C., Gilani, H. and Bajracharya, B., (2016). Mapping Deforestation and Forest Degradation Patterns in Western Himalaya, Pakistan. Remote Sensing. 11(7), pp.831
Used satellite images to generate sub-district level statistics for forest cover over the Western Himalaya in Pakistan. The digital classification was reviewed by professionals with backgrounds in remote sensing and a strong ecological knowledge of the local area (including experts from the WWF-Pakistan, Karakorum International University and the National Agriculture Research Centre). This was to check for misinterpretations in the digital classification that may have been caused by environmental conditions at the time of image acquisition (e.g., clouds, fog), variations in local forest types or limitations in computational algorithms.

References:
Martin, D., (1998). 2001 Census output areas: from concept to prototype. Population Trends. 94, pp.19-24.
ONS., (2021). Consultation response: Census 2021 Output Geography Policy, Products and Services [online]. London: ONS. [Viewed 27 July 2021]. Available from: https://consultations.ons.gov.uk/external-affairs/ons-2021-census-output-geography-policy-products-a/results/2021geographyoutputsconsultation_response_v5.pdf
Tower Hamlets., (2013). Research Briefing: A Guide to Census Geography [online]. London: Tower Hamlets. [Viewed 27 July 2021]. Available from: https://www.towerhamlets.gov.uk/Documents/Borough_statistics/Research-tools-and-guidance/RB-Census2011-Census-Geography-Guide-2013-05.pdf

Other useful sources:
Copy of consultation questionnaire from 2011 consultation: https://www.mrs.org.uk/pdf/MRS_CGG_Geography_consultation_response.pdf
Martin, D., (1998). 2001 Census output areas: from concept to prototype. Population Trends. 94, pp.19-24. – Outlines the process of using GIS to create the output areas – doesn’t discuss validation.
