---
title: "Minority Communities in Derry/Londonderry"
output: html_document
---
https://www.bbc.co.uk/northernireland/schools/11_16/citizenship/pdfs/ctz_eth_pg02_tn.pdf
-	According to 2001 Census data, in Foyle (The parliamentary constituency in Derry), there are a total of 962 ethnic minority residents out of a population of 105,078 (0.92%).
-	Due to its more remote physical location, political instability, and the fact that Northern Ireland is one of the poorest regions in the UK so there are a lack of jobs and business opportunities, Northern Ireland has never seen a significant inflow of people.
-	Populations of Indian, Bangladeshi, Pakistani and Chinese immigrants (mostly from Hong Kong) migrated when their home countries were part of the British Empire. C.60% of Chinese people living in Northern Ireland were born there.
-	Irish travellers are one of the largest ethnic groups in Northern Ireland.
-	Nearly a third of those belonging to ethnic minority communities live in Belfast.
-	The number of people born in non-UK EU Countries as of 2001 was 406 in Foyle (0.39%).


https://www.ninis2.nisra.gov.uk/public/PivotGrid.aspx?ds=1114&lh=37&yn=2007-2009&sk=74&sn=Population&yearfilter=
-	As of 2009 there were 800 Central and Eastern European Migrants in Derry (0.7% of total population).


Table showing the number of people identifying as different ethnic groups in the 2011 Census (Derry City and Strabane): https://www.ninis2.nisra.gov.uk/public/PivotGrid.aspx?ds=7468&lh=73&yn=2011&sk=136&sn=Census%202011&yearfilter=
-	The population is 98.53% White, with the next largest communities being Indian (0.45%), Mixed (0.31%) and Chinese (0.2%).


There are thought to be 30000 Polish people living in Northern Ireland, with many moving following Poland joining the EU in search of work. (As of 2007). (http://news.bbc.co.uk/1/hi/northern_ireland/6251117.stm; https://en.wikipedia.org/wiki/Immigrant_communities_in_Northern_Ireland).


Derry City & Strabane District Council Good Relations Team Publication: https://www.derrystrabane.com/getmedia/c23b6fc6-c6e3-4095-a96c-c66026b8a7fd/Good-relations.pdf
-	According to the 2011 Census there are 3696 people living in the area who were born outside of the UK and Republic of Ireland. This is 2.5% of the population, lower than the 4.5% average across Northern Ireland.
o	Includes Asian (mainly Chinese, Indian and Filipino); Eastern European (mainly Polish); African and Middle Eastern Communities.
o	2000 residents aged 3 and over have a language other than Enlgihs or Irish as their main language. Of them, 23% cannot speak English well or at all. Polish, Malayalam (an Indian language), Chinese and Tagalog (a Filipino language) are some of the main minority ethnic languages.
o	Top reasons for moving were Family (41%), Work (29%) and Education (10%).
-	921 racially motivated hate crimes were recorded in Northern Ireland in 2014/15. 110 of these were in the ‘G’ District that covers the North West. C.10% of these attacks were on children.
https://www.bbc.co.uk/news/uk-northern-ireland-49435877
In 2018, net migration to Northern Ireland reached a 10-year peak. It was the fifth year in a row in which the migrant population increased.
Derry City was one of only two council districts to experience a net outflow of international migrants.


Findings of the Northern Ireland Life and Times Survey showed high levels of racist, Islamophobic and xenophobic views among a significant minority (https://www.derryjournal.com/news/crime/race-hate-spike-in-derry-reported-alongside-intolerance-among-18-to-24-year-olds-against-eastern-europeans-and-muslims-3167339):
-	Whilst there was a trend of decreasing levels of hate crimes across the north, Derry and Strabane recorded an increase.
-	Fewer people reported having black friends than in previous years. Only 14% of respondents report having Black friends in 2019. This figure has steadily declined from 19% five years previously.
-	There were high levels of slavophobia and intolerance towards other Eastern European peoples and nationalities amongst young people. The survey found that in 2017 38% of 18- to 24-year-olds would not accept an Eastern European as a friend. This fell to 13% in 2018 and 9% in 2019.
-	Persistently high levels of Islamophobia were evident across the Six Counties. One third of 18- to 24-year-olds wouldn’t accept a Muslim as a neighbour in their local area, the only age group higher than this is the over 65s. 31% of respondents aged 18 to 24 said that they would not accept a Muslim as a close friend in 2019.
o	This is particularly concerning as one third of Derry’s population are aged under 25, meaning that these responses represent a large proportion of the population (https://www.derryjournal.com/news/environment/opinion-derry-irelands-only-shrinking-city-steve-bradley-3171626).
-	According to PSNI data, hate crime had increased in 2020. Although there was a reduction in racist incidents and crimes from January to December 2020, in Derry there was an increase of 12 racist incidents and an increase of 13 racist crimes in this time. Derry and Strabane saw the greatest increase in racist incidents from January 2019 to December 2020 and the second highest increase in racist crimes from January to December. This was during lockdown so was a particular cause for concern.
-	By comparison, during the same period, the number of sectarian incidents in Derry and Strabane decreased by 49 cases and sectarian crimes decreased by 42 cases.
-	Foyle Racial Equality Forum noted that there are a large number of cases that do not get reported.


https://www.derryjournal.com/news/politics/29-self-report-prejudice-against-minority-ethnic-groups-with-rise-in-racist-incidents-crimes-and-bullying-and-harassment-in-schools-3184979
-	Graphic showing a breakdown of self-reported prejudice by gender, religion and age is included in the article.
-	The results of the ‘Northern Ireland Racial Equality Indicators Report: 2014-2019’ were published in March 2021. It presents data measuring progress on the Racial Equality Strategy 2015 – 2025 on 4 key areas: equality of service provision; combating prejudice, racism and hate crime; participation, representation and belonging; respecting cultural diversity.
-	In 2019, the proportion of respondents self-reporting prejudice against people from minority ethnic communities had increased significantly: in 2014 the baseline was 24%, this dropped to 20% in 2018 before rising again to 29% in 2019.
-	In spite of this, there was a significant decrease in the proportion of respondents thinking that there is more racial prejudice against people from minority ethnic communities than 5 years ago (2014: 52%, 2018: 41%, 2019: 30%).
-	The number of racist incidents reported has also increased from the baseline of 976 in 2013/14 to 1124 in 2018/19. The number of racist crimes also increased (2013/14: 688, 2018/19: 699). There was a significant increase in the proportion of respondents who reported that they had witnessed racist bullying or harassment in their school, with the figure for 2019 at 45%, compared to 39% in 2014.
-	There has been an increase in the acceptance of some groups, with willingness to accept Eastern European, Irish Traveller and Muslims as residents, work colleagues or family members all increasing significantly since the baseline.
-	There appears to have been improvement in the educational attainment for all groups, but gaps in achievement and inequality persist. Since 2013/14, there has been an increase of around 7% for both White and minority ethnic pupils leaving school with 5 GCSEs (Grade A*-C). White: 86.5%, minority ethnic: 82.4%. There has been little change in the proportion of White school leaves with no qualifications (2013/14: 0.7%; 2018/19: 0.6%) and a decrease in the percentage of minority ethnic school leavers with no qualifications (2013/14: 5.8%, 2018/19: 2.2%).
-	Compared to the baseline, there has been a significant decrease in the proportion of respondents who thought that minority ethnic people participated ‘a little’ or ‘a lot’ in public life: 2014: 71%, 2019: 57%.
-	A significantly higher proportion of respondents aged 16 years in 2019 said that they socialised or played sport with people from a different ethnic background than in 2014 – increased from 54% to 62%.
-	Following the basline, there has been no significant change in the percentage of respondents who agreed that the culture and traditions of the minority ethnic community added to the richness and diversity of Northern Ireland (2014: 59%; 2019: 61%). However, there was a significant decrease from 2018 to 2019 (2018: 65%).
-	The percentage of people with friends from minority ethnic communities has increased from the baseline of 42% to 53%.



Report that may be useful – The Roma Community in Northern Ireland and housing: A Scoping Review (https://www.nihe.gov.uk/Documents/Research/Shared-Communities-Page/Roma-community-Northern-Ireland-and-Housing.aspx?ext=.)
