---
title: "Untitled"
author: "Lydia Warden"
date: "03/08/2021"
output: html_document
---
Derry (Londonderry): background information (https://en.wikipedia.org/wiki/Derry)
-	¬There is much contestation around the name of the city, officially named Londonderry but referred to as simply Derry by many. Derry City Council conducted an opinion poll in 2009 to gauge opinions on officially changing the city’s name to Derry. 75% of Catholics and 77% of Nationalists would accept the proposed change, compared to 6% of Protestants and 8% of Unionists. However, in everyday conversation, ‘Derry’ is used by most Protestant residents of the city.
-	Derry played an important role in the Second World War, with large numbers of military personnel based there from a range of allied nations. This ‘substantially altered the character of the city’, increasing its diversity, cosmopolitanism and boosting the economy.
-	The Troubles were widely believed to have started in Derry. During the early 1970s there was a strong military presence and widespread civil unrest. Several districts constructed barricades to control access and prevent forces from entering.
-	2011 Census: 105,066 population. 75% Roman Catholic, 23% Protestant (an increase of 3 percent from 2001).
-	The population of Protestants in the city has significantly decreased since the 1970s, with fears raised that the city could become permanently divided.
-	Industry:
o	There was previously a strong textiles industry in Derry, but this largely disappeared due to overseas competition.

Waterside: background information
-	The half of the city west of the river Foyle is known as the Cityside and the area east is called the Waterside. (https://en.wikipedia.org/wiki/Derry)
-	Geography: Waterside refers to the part of Derry on the east bank of the Foyle. This ends at the Caw roundabout near Foyle Bridge. Areas including Eglinton and Limavady are not part of the Waterside. (https://en.wikipedia.org/wiki/Waterside,_Derry)
-	The Waterside is mainly Protestant and unionist, whereas the rest of Derry is mainly Irish Catholic and nationalist. Waterside’s Protestant population grew during the Troubles. (https://en.wikipedia.org/wiki/Waterside,_Derry)



Shirlow, P., Graham, B., McMullan, A., Murtagh, B., Robinsons, G. and Southern, N., (2005). Population Change and Social Inclusion Study Derry/Londonderry. https://cain.ulster.ac.uk/issues/population/popchangederry05.pdf


-	P5 In 2001, approximately 75% of the 105,066 residents of the Derry District Council Area (DDCA) came from a Catholic community background. The population of Derry itself was c.93000, 59% of whom resided in the Cityside, with the remainder living in the Waterside. The Cityside is majority Catholic, whereas the Waterside’s population is virtually evenly divided between Protestants and Catholics.
-	All respondents self-identified as Protestant or as having come from a Protestant background.
-	Objectives:
o	‘to determine the quantitative extent of separation/sharing between Protestants and the “other” community;
o	To examine the meaning of this separation/sharing for Protestants;
o	To establish if claims of Protestant alienation reflect the views of the community;
o	To assess the impact of population decline and out-migration upon the Protestant population;
o	P6 To produce an envisioning document that seeks to establish the structures and policies needed to encourage new forms of co-operation and sharing in Derry/Londonderry.’
-	P6 Principal methods: analysis of secondary census data; policy audit; detailed questionnaire survey of 400 Protestant households; focus groups; semi-structured interviews.

Chapter 1: Cultural and Political Change and the Protestant Community of Derry/Londonderry
-	‘The empirical evidence confirming a significant movement of Protestants from the Cityside is more complex than it might seem but still creates the spatial context for the study of Protestant marginalisation in the city.
-	Widely held belief that the minority Protestant population in the DDCA is in demographic and political decline due to a combination of out-migration and social and cultural change. Demographic decline has, however, halted.
-	Many interview respondents argued that the Protestant population has been ‘undermined’ by the political, economic and cultural growth of Irish nationalism/republicanism. Minority representation at a council level has led to feelings of political powerlessness, which operate alongside a strong feeling that nationalists/republicans do not recognise Protestant needs.
-	P10 ‘…the hostility generated by senses of alienation is not merely sectarian but is also directed towards certain political outcomes. Nevertheless, despite the obvious political difficulties created by such hostility, there are also signs of increased engagement, ecumenical activity and social interaction between Protestant and nationalist communities. This interaction within places that are predominantly Catholic is noted within the survey findings.’
-	P11 Different groups within the Protestant community experience alienation in varying ways. Senses of marginalisation are relative concepts, varying by class, gender, age and geography. Additionally, the decline in violence in Derry/Londonderry has altered mobility patterns.
-	P12 Most respondents identified a series of political developments which they stood to have undermined unionism. 11.8% believed that Protestants/unionists had benefitted more or a lot more than nationalists and republicans from the Belfast Agreement, compared to 53.4% who believed they had benefitted less.
-	P13 Less than 20% of Protestants said that they believed that they had an equal political say in the development of Derry/Londonderry.
-	P14 Over 2/3 of respondents felt that their culture is in decline. This related to the strong belief that Protestant cultural traditions are not protected; a common perception is ‘that Irish culture is funded and encouraged and British culture is denigrated and denied.’
-	The apparent Protestant retreat to the Waterside and elsewhere has defined the city’s absolute ethno-sectarian geography and increased problems associated with ethnic difference.
-	P15 increased interconnectedness between Protestant areas and consumer precincts in the Cityside (2/3 of respondents agreed that ‘Protestants are more likely to shop in Catholic places’.)
-	C.90% of respondents had never been victims of verbal abuse or emotional or physical violence in the previous 25 years => perceptions of violence has had a greater effect on mobility than direct experience of such violence. Perceptions of violence are understood as being aimed at a community than an individual.

P20 Chapter 2: Population Trends in Derry/Londonderry, 1991-2001.
-	Uses 1991 and 2001 census data to understand that demographic context, changing trends in DDCA over the decade and the spatial pattern of segregation in the DDCA.
-	Between 1971 and 1991, the Protestant population of the DDCA declined by an estimated 31%, compared to a 36% growth in the Catholic population.
-	In the same period, the Protestant population of the Cityside declined by 83.4%, matched by a 27% growth in the Protestant population in the Waterside. P20-21 This is thought to be mainly due to the out-migration of Protestants from the Cityside to the Waterside.
-	P22 three problems complicate comparison of the 1991 and 2001 census: there was an increase in 2001 of those refusing to state religious affiliation; the 2001 census included a question on community background which can be used as an alternative but makes direct comparison with the 1991 data more difficult; data collection units in 1991 were altered in 2001.
-	In 1991, 69.4% of the c95000 population identified as Catholic, vs 20.9% Protestant. There was an increase of 12.4% in the Catholic population between 1991 and 2001, compared to a marginal increase of 0.4% in the Protestant population.
-	P23 Broad spatial trends: the EDs/OAs in the Waterside area show greater spatial variation than the Cityside, which is mostly Catholic.
-	P25 In 2001, approximately half of those who designated themselves as Catholic and almost three quarters of those from a Catholic community background lived in areas where the population was 91-100% Catholic.
-	P26 In 1991, the Waterside population was 45.3% Protestant and 41.5% Catholic. By 2001, that trend had reversed, with 44.9% of the population Catholic and 41.5% Protestant. Both populations increased from 1991 to 2001, but the rate of increase was much higher for the Catholic population.
o	When information on community background is used, the proportion of people from a Protestant community background (49.5%) is greater than from a Catholic community background (48.3%).
o	P27 The proportion of Protestant and Catholic communities living in segregated areas (61-100% Protestant/Catholic) is 62.6% and 90.2% respectively when community background data is considered.

P32 Chapter 3: Questionnaire Survey Findings
-	399 respondents
-	Aimed to examine issues of segregation and cultural and political alienation and conflict amelioration in Derry/Londonderry.
-	P33 Around half of the respondents had moved to their present address. Of them, 8.1% had moved due to the previous area being unsafe. 3.3% had moved due to the previous area being dominated by the ‘other’ community. 4.3% had moved due to intimidation.
-	P34 97% of respondents stated that the Troubles were the cause of high levels of segregation. 87.2% agreed or strongly agreed that segregation creates poor community relationships.
-	52.6% felt that housing policy aided the reproduction of segregation.
-	93.9% of respondents believed that ‘Protestants feel safer living within predominantly Protestant places’. 51% believed that their community does not want to share space with the ‘other’ community. 65.2% believed that the ‘other’ community wanted their community ‘to move out of the city’.
-	20% agreed or strongly agreed that the ‘other’ community would welcome ‘greater mixing between my community and theirs’. Half disagreed or strongly disagreed.
-	P36 the majority of respondents (82.2%) considered themselves to be British. Northern Irish was the second-most common answer (14.2%). 4% preferred to be thought of as Irish. Ulster, Scottish and English each received between 1 and 2%.
-	Approximately half of respondents were ‘very proud’ of being British, compared to 3.5% who were ‘very proud’ to be Irish. One quarter stated they were ‘somewhat proud’ of being Irish. 4.5% did not see themselves as being British, compared to 57.7% who did not consider themselves to be Irish.
-	P38 significant variations based on age and gender.
-	P43 Significant findings that respondents felt that Catholics had better access to resources and educational opportunities than Protestants.
-	P45 82.6% of respondents had never been treated unfairly in a shop/business due to their religion. The majority of those in employment work in predominantly Catholic workplaces (61%), compared to 34% who do not. 56.5% of respondents had worked in a predominantly Catholic workplace during some period of their careers, with 9.7% stating that they would feel ‘uneasy’ doing so again. 17.2% would consider working in a predominantly Catholic workplace again. 59.9% would be content to work in such places. C.1/4 of respondents said they would not consider working ‘in a place where the majority of employees are Catholic’.
-	P46 47.8% of respondents felt that members of their own community were discriminated against when seeking work (18.9% answered maybe).
-	P52 Findings reveal that a high percentage of Protestants: feel that their community is in a state of decline; believe that segregation will continue (but they want it to continue); uphold the notion that their cultural identity is both in decline and unprotected within the city; interpret equality agendas as favouring the majority community within the DDCA area.

P54 Chapter 4: Perspectives on Place, Politics and Culture.
-	Focus groups: 9 drawn from Protestant community, 3 drawn from Catholic community.
-	P55 the survey finding that only a minority of Protestants had ever been the subject of verbal or physical abuse (either in the last 5 or 25 years) was confirmed by the majority of FG participants.
-	P56 many participants supported the finding that the majority were happy to shop in the Cityside. Some confirmed that they would shop there but that there were particular areas of the Cityside where they would feel more comfortable than others.
-	P57 The general consensus was that people go there to shop but they park nearby the shops they need to visit, purchase what they need, and leave straight away.
-	P59 Former Cityside Protestants spoke with regret a strong sense of emotional loss about their move to the Waterside.
-	P66 Protestants are concerned by the rate of demographic change taking place in the Waterside. Some felt that a rise in the Catholic population will have negative effects for the Protestant community. This sense of threat was generally felt more strongly in working-class areas where segregation is the norm.
-	P69 Whilst a substantial minority of Protestants who responded to the survey stated that they would not be bothered by changing the city’s name, this emerged through the focus groups as a significant source of potential Protestant alienation. They emphasised its importance to their identity, and that the proposal to remove ‘London’ was ‘an ideologically-driven attempt to rid the city of its Britishness’. It would put further pressure on the identification that Protestants feel with the city, with respondents stating that they already “feel that we’re sort of strangers in our own place”.

P97 Chapter 6: Conclusion
-	P101-2 Conflict transformation: there is a danger that Protestants may be disconnected from wider social, economic, policy and pol
